version: '3.8'

services:
  s3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4568:4568" 
    volumes:
      - ./data/s3-buckets:/app/s3-buckets  # Persiste les données des fichiers
